### ISSUE TITLE
自动构建的话，能否把requirement.txt加入到镜像中

### ISSUE THREAD

**Issue by zealseeker** [DaoCloud/python-ipython-notebook#12]
之前开了一个Dockerfile构建库在github上，里面除了Dockerfile还有一个我需要ADD 一个自己修改的文件然后进行编译

可我发现无论是用ADD （https://hub.docker.com/r/zealseeker/rdkit-draw/builds/b33rd4kh6agyjzrqalpo3he/）
还是用COPY （https://hub.docker.com/r/zealseeker/rdkit-draw/builds/b33rd4kh6agyjzrqalpo3he/）
尽管最终都编译成功，但是打开发现，源文件中并没有覆盖我需要修改的文件。
最终我只能通过wget的方法获取文件（https://github.com/zealseeker/rdkit-draw/blob/master/Dockerfile#L7）

所以想问， 这是docker hub的问题还是我的问题？如果是docker hub的问题，daocloud是否可以自动构建，添加开源库内的文件呢？

**Comment by sakeven** [comment]
是这句 ```ADD ./rdMolDraw2D.cpp ~/rdkit-Release_2016_03_1/Code/GraphMol/MolDraw2D/Wrap/```执行的时候，不在root用户下，所以~是有问题的，可以替换成 /root。

PS： 不用我们 DaoCloud 构建，这样真的大丈夫？

**Comment by zealseeker** [comment]
@sakeven 原来是这样~ 看来对docker还是不够熟~  谢谢。 将来用DaoCloud构建哈，可能pull速度会快点~~

**Comment by sakeven** [comment]
@zealseeker 说错了，是在 root 用户下，但是~/...这串是相对地址，实际上会生成 $work_dir/~/....
